# 参考https://golangci-lint.run/usage/configuration/#run-configuration
# 设置执行时的配置,如并发数,是否跳过测试文件,跳过某些目录等等
run:
  timeout: 10m
  modules-download-mode: readonly
  tests: false # 不检查测试文件
  # 设置输出的选项,如显示格式等等
output:

linters:
  disable-all: true # 设置为全部关闭,只开启我们想要设置的linter
  enable:
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    # 新增 linter
    - gofmt # 检查是否经过gofmt格式化
    - goimports # 检查是否经过goimports格式化
    - nolintlint # 检查设置了nolint的地方是否添加了原因
    - gofumpt # 检查是否被gofumpt格式化过
    - gocritic # 更严格代码检查
    - cyclop # 代码圈复杂度,最好在10以下

    #- lll # 单行长度限制
    - revive # 更严格代码检查

    #- wsl # 强制使用空行
    #- errorlint # 强制使用1.13的错误机制

    # 每个linter的定制化选项
linters-settings:
  gofumpt:
    module-path: github.com/leilei3167/ci # 必须设置为go.mod的项目名称,否则将一直报错
    extra-rules: false
  cyclop:
    # The maximal code complexity to report.
    # Default: 10
    max-complexity: 15
    # The maximal average package complexity.
    # If it's higher than 0.0 (float) the check is enabled
    # Default: 0.0
    package-average: 0.0
    # Should ignore tests.
    # Default: false
    skip-tests: true

  godot:
    # Comments to be checked: `declarations`, `toplevel`, or `all`.
    # Default: declarations
    scope: toplevel
    # List of regexps for excluding particular comment lines from check.
    # Default: []
    exclude:
      # Exclude todo and fixme comments.
      - "^fixme:"
      - "^todo:"
      - "^FIXME:"
      - "^TODO:"
    # Check that each sentence ends with a period.
    # Default: true
    period: true
    # Check that each sentence starts with a capital letter.
    # Default: false
    capital: true

  lll:
    # Max line length, lines longer will be reported.
    # '\t' is counted as 1 character by default, and can be changed with the tab-width option.
    # Default: 120.
    line-length: 140
    # Tab width in spaces.
    # Default: 1
    tab-width: 1

issues:

severity:
